version 1.0

import "https://raw.githubusercontent.com/getwilds/wilds-wdl-library/refs/heads/main/modules/ww-fastqc/ww-fastqc.wdl" as fastqc_tasks
import "https://raw.githubusercontent.com/getwilds/wilds-wdl-library/refs/heads/main/modules/ww-trimgalore/ww-trimgalore.wdl" as trimgalore_tasks
import "https://raw.githubusercontent.com/getwilds/wilds-wdl-library/refs/heads/main/modules/ww-star/ww-star.wdl" as star_tasks
import "https://raw.githubusercontent.com/getwilds/wilds-wdl-library/refs/heads/main/modules/ww-bedparse/ww-bedparse.wdl" as bedparse_tasks
import "https://raw.githubusercontent.com/getwilds/wilds-wdl-library/refs/heads/main/modules/ww-rseqc/ww-rseqc.wdl" as rseqc_tasks
import "https://raw.githubusercontent.com/getwilds/wilds-wdl-library/refs/heads/rnaseq-feedback/modules/ww-deseq2/ww-deseq2.wdl" as deseq2_tasks
import "https://raw.githubusercontent.com/getwilds/wilds-wdl-library/refs/heads/main/modules/ww-multiqc/ww-multiqc.wdl" as multiqc_tasks
import "https://raw.githubusercontent.com/getwilds/wilds-wdl-library/refs/heads/main/modules/ww-gffread/ww-gffread.wdl" as gffread_tasks

struct RefGenome {
    String name
    File fasta
    File gtf
}

workflow rnaseq {
  meta {
    author: "Taylor Firman"
    email: "tfirman@fredhutch.org"
    description: "Comprehensive RNA-seq pipeline covering read QC, adapter trimming, alignment, post-alignment QC, differential expression, and aggregated reporting"
    url: "https://raw.githubusercontent.com/getwilds/wilds-wdl-library/refs/heads/main/pipelines/ww-rnaseq/ww-rnaseq.wdl"
    outputs: {
        pretrim_fastqc_html: "FastQC HTML reports for raw reads (pre-trimming) for each sample",
        pretrim_fastqc_zip: "FastQC ZIP archives for raw reads (pre-trimming) for each sample",
        trimgalore_r1_trimmed: "Trimmed R1 FASTQ files for each sample",
        trimgalore_r2_trimmed: "Trimmed R2 FASTQ files for each sample",
        trimgalore_r1_report: "Trim Galore trimming reports for R1 for each sample",
        trimgalore_r2_report: "Trim Galore trimming reports for R2 for each sample",
        posttrim_fastqc_html: "FastQC HTML reports for trimmed reads (post-trimming) for each sample",
        posttrim_fastqc_zip: "FastQC ZIP archives for trimmed reads (post-trimming) for each sample",
        star_bam: "STAR alignment output BAM files for each sample",
        star_bai: "Index files for the STAR alignment BAM files",
        star_gene_counts: "Gene count files generated by STAR for each sample",
        star_log_final: "Final log files from STAR alignment for each sample",
        star_log_progress: "Progress log files from STAR alignment for each sample",
        star_log: "Main log files from STAR alignment for each sample",
        star_sj: "Splice junction files from STAR alignment for each sample",
        rseqc_qc_summary: "Quality control summary reports produced by RSeQC for each sample",
        combined_counts_matrix: "Matrix file containing combined gene counts from all samples",
        sample_metadata: "Metadata file containing sample information and conditions",
        deseq2_all_results: "Complete DESeq2 differential expression results for all genes",
        deseq2_significant_results: "Filtered DESeq2 results containing only significant differentially expressed genes",
        deseq2_normalized_counts: "Normalized count values produced by DESeq2",
        deseq2_pca_plot: "Principal Component Analysis plot of samples based on expression patterns",
        deseq2_volcano_plot: "Volcano plot showing log fold change vs. statistical significance",
        deseq2_heatmap: "Heatmap of differentially expressed genes across samples",
        deseq2_compiled_results: "Combined CSV with DESeq2 statistics, normalized counts, and gene annotations",
        multiqc_report: "MultiQC interactive HTML report aggregating all QC metrics",
        multiqc_data: "MultiQC data directory with parsed metrics from all tools"
    }
  }

  parameter_meta {
    samples_tsv: "Tab-separated file with columns: name, r1, r2, condition (header row required). Alternative to providing separate arrays."
    sample_names: "Array of sample names (use with r1_fastqs, r2_fastqs, conditions as alternative to samples_tsv)"
    r1_fastqs: "Array of R1 FASTQ file paths, one per sample"
    r2_fastqs: "Array of R2 FASTQ file paths, one per sample"
    conditions: "Array of condition labels for each sample (e.g., 'control', 'treatment')"
    reference_genome: "Reference genome object containing name, fasta, and gtf files"
    reference_level: "Reference level for DESeq2 contrast (e.g., 'control' when comparing treatment vs. control)"
    contrast: "DESeq2 contrast string in the format 'condition,treatment,control'"
    trim_quality: "Quality threshold for Trim Galore adapter/quality trimming"
    trim_length: "Minimum read length to retain after trimming"
    star_cpu: "Number of CPU cores for STAR alignment tasks"
    star_memory_gb: "Memory allocation in GB for STAR alignment tasks"
    genome_sa_index_nbases: "Length of the SA pre-indexing string for STAR (typically 10-15, scales with genome size)"
  }

  input {
    # Option 1: Provide a TSV file with columns name, r1, r2, condition
    File? samples_tsv
    # Option 2: Provide separate arrays directly
    Array[String]? sample_names
    Array[File]? r1_fastqs
    Array[File]? r2_fastqs
    Array[String]? conditions
    RefGenome reference_genome
    String reference_level = ""
    String contrast = ""
    Int trim_quality = 20
    Int trim_length = 20
    Int star_cpu = 8
    Int star_memory_gb = 64
    Int genome_sa_index_nbases = 14
  }

  # Parse sample information from TSV if provided.
  # TSV format: tab-separated with header row (name, r1, r2, condition).
  # Header row is skipped by offsetting indices by +1 in the scatter below.
  Array[Array[String]] tsv_rows = if defined(samples_tsv) then read_tsv(select_first([samples_tsv])) else []

  # Determine number of samples from whichever input method was used
  # For TSV: subtract 1 to exclude the header row
  Int n_samples = if defined(sample_names) then length(select_first([sample_names])) else (length(tsv_rows) - 1)
  Array[Int] sample_indices = range(n_samples)

  # Normalize GTF to ensure exon features exist for every transcript.
  # This is critical for bacterial NCBI GTFs which only have CDS rows —
  # without this step, STAR GeneCounts and RSeQC would silently ignore
  # 98% of protein-coding genes. For eukaryotic GTFs this is a pass-through.
  call gffread_tasks.normalize_gtf { input:
      input_gtf = reference_genome.gtf
  }

  # Build STAR genome index (runs once)
  call star_tasks.build_index { input:
      reference_fasta = reference_genome.fasta,
      reference_gtf = normalize_gtf.normalized_gtf,
      cpu_cores = star_cpu,
      memory_gb = star_memory_gb,
      genome_sa_index_nbases = genome_sa_index_nbases
  }

  # Convert GTF to BED for RSeQC
  call bedparse_tasks.gtf2bed { input:
      gtf_file = normalize_gtf.normalized_gtf
  }

  scatter (idx in sample_indices) {
    # Offset index by 1 to skip the TSV header row
    Int tsv_idx = idx + 1
    String sample_name = if defined(sample_names) then select_first([sample_names])[idx] else tsv_rows[tsv_idx][0]
    File sample_r1 = if defined(r1_fastqs) then select_first([r1_fastqs])[idx] else tsv_rows[tsv_idx][1]
    File sample_r2 = if defined(r2_fastqs) then select_first([r2_fastqs])[idx] else tsv_rows[tsv_idx][2]
    String sample_condition = if defined(conditions) then select_first([conditions])[idx] else tsv_rows[tsv_idx][3]

    # Step 1: Pre-trim FastQC
    call fastqc_tasks.run_fastqc as step01_pretrim_fastqc { input:
        r1_fastq = sample_r1,
        r2_fastq = sample_r2
    }

    # Step 2: Trim Galore adapter/quality trimming
    call trimgalore_tasks.trimgalore_paired as step02_trimgalore { input:
        sample_name = sample_name,
        r1_fastq = sample_r1,
        r2_fastq = sample_r2,
        quality = trim_quality,
        length = trim_length
    }

    # Step 3: Post-trim FastQC
    call fastqc_tasks.run_fastqc as step03_posttrim_fastqc { input:
        r1_fastq = step02_trimgalore.r1_trimmed,
        r2_fastq = step02_trimgalore.r2_trimmed
    }

    # Step 4: STAR two-pass alignment on trimmed reads
    call star_tasks.align_two_pass as step04_star_align { input:
        star_genome_tar = build_index.star_index_tar,
        r1 = step02_trimgalore.r1_trimmed,
        r2 = step02_trimgalore.r2_trimmed,
        name = sample_name + "." + reference_genome.name,
        cpu_cores = star_cpu,
        memory_gb = star_memory_gb
    }

    # Step 5: RSeQC alignment quality control
    call rseqc_tasks.run_rseqc as step05_rseqc { input:
        sample_name = sample_name,
        bam_file = step04_star_align.bam,
        bam_index = step04_star_align.bai,
        ref_bed = gtf2bed.bed_file
    }
  }

  # Step 6: DESeq2 count matrix assembly and differential expression
  call deseq2_tasks.combine_count_matrices as step06_combine_counts { input:
      gene_count_files = step04_star_align.gene_counts,
      sample_names = sample_name,
      sample_conditions = sample_condition
  }

  call deseq2_tasks.run_deseq2 as step07_deseq2 { input:
      counts_matrix = step06_combine_counts.counts_matrix,
      sample_metadata = step06_combine_counts.sample_metadata,
      reference_level = reference_level,
      contrast = contrast
  }

  # Step 8: Compile DESeq2 results with normalized counts and GTF annotations
  call deseq2_tasks.compile_deseq2_results as step08_compile_results { input:
      deseq2_results = step07_deseq2.deseq2_results,
      normalized_counts = step07_deseq2.deseq2_normalized_counts,
      gtf_file = normalize_gtf.normalized_gtf
  }

  # Step 9: MultiQC aggregation of all QC reports
  call multiqc_tasks.run_multiqc as step09_multiqc { input:
      input_files = flatten([
        flatten(step01_pretrim_fastqc.html_reports),
        flatten(step01_pretrim_fastqc.zip_reports),
        step02_trimgalore.r1_report,
        step02_trimgalore.r2_report,
        flatten(step03_posttrim_fastqc.html_reports),
        flatten(step03_posttrim_fastqc.zip_reports),
        step04_star_align.log_final,
        step05_rseqc.rseqc_summary
      ]),
      report_title = "RNA-seq Pipeline QC Report"
  }

  output {
    Array[Array[File]] pretrim_fastqc_html = step01_pretrim_fastqc.html_reports
    Array[Array[File]] pretrim_fastqc_zip = step01_pretrim_fastqc.zip_reports
    Array[File] trimgalore_r1_trimmed = step02_trimgalore.r1_trimmed
    Array[File] trimgalore_r2_trimmed = step02_trimgalore.r2_trimmed
    Array[File] trimgalore_r1_report = step02_trimgalore.r1_report
    Array[File] trimgalore_r2_report = step02_trimgalore.r2_report
    Array[Array[File]] posttrim_fastqc_html = step03_posttrim_fastqc.html_reports
    Array[Array[File]] posttrim_fastqc_zip = step03_posttrim_fastqc.zip_reports
    Array[File] star_bam = step04_star_align.bam
    Array[File] star_bai = step04_star_align.bai
    Array[File] star_gene_counts = step04_star_align.gene_counts
    Array[File] star_log_final = step04_star_align.log_final
    Array[File] star_log_progress = step04_star_align.log_progress
    Array[File] star_log = step04_star_align.log
    Array[File] star_sj = step04_star_align.sj_out
    Array[File] rseqc_qc_summary = step05_rseqc.rseqc_summary
    File combined_counts_matrix = step06_combine_counts.counts_matrix
    File sample_metadata = step06_combine_counts.sample_metadata
    File deseq2_all_results = step07_deseq2.deseq2_results
    File deseq2_significant_results = step07_deseq2.deseq2_significant
    File deseq2_normalized_counts = step07_deseq2.deseq2_normalized_counts
    File deseq2_pca_plot = step07_deseq2.deseq2_pca_plot
    File deseq2_volcano_plot = step07_deseq2.deseq2_volcano_plot
    File deseq2_heatmap = step07_deseq2.deseq2_heatmap
    File deseq2_compiled_results = step08_compile_results.compiled_results
    File multiqc_report = step09_multiqc.html_report
    File multiqc_data = step09_multiqc.data_dir
  }
}
