name: WDL Workflow Test Run

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**.wdl'
      - '.github/workflows/testrun.yml'

jobs:
  miniwdl-test:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - 
      name: Install miniwdl
      run: |
        python -m pip install --upgrade pip
        pip3 install miniwdl
    - 
      name: Run workflow with miniwdl
      run: |
        mkdir -p test-output/miniwdl
        miniwdl run modules/ww-sra/ww-sra.wdl -i modules/ww-sra/inputs.json --dir test-output/miniwdl
    - 
      name: Display validation report
      run: |
        echo "=== MiniWDL Validation Report ==="
        find test-output/miniwdl -name "validation_report.txt" -exec cat {} \;
  
  cromwell-test:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Set Up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - 
      name: Download Cromwell
      run: |
        wget -q https://github.com/broadinstitute/cromwell/releases/download/86/cromwell-86.jar
    - 
      name: Run workflow with Cromwell
      run: |
        mkdir -p test-output/cromwell
        java -jar cromwell-86.jar run modules/ww-sra/ww-sra.wdl -i modules/ww-sra/inputs.json -o modules/ww-sra/options.json
    - 
      name: Display validation report
      run: |
        echo "=== Cromwell Validation Report ==="
        find . -name "validation_report.txt" -exec cat {} \;
  
  sprocket-test:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Set Up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - 
      name: Install cargo-binstall
      run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - 
      name: Install Sprocket
      run: cargo-binstall sprocket --version 0.12.2
    - 
      name: Run workflow with Sprocket
      run: sprocket run --output test-output/sprocket modules/ww-sra/ww-sra.wdl modules/ww-sra/inputs.json
    - 
      name: Display validation report
      run: |
        echo "=== Sprocket Validation Report ==="
        find test-output/sprocket -name "validation_report.txt" -exec cat {} \;
