name: WDL Workflow Test Run

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'modules/**/*.wdl'
      - 'modules/**/*.json'
      - '.github/workflows/testrun.yml'

permissions:
  contents: read

jobs:
  discover-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.find-modules.outputs.modules }}
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Find WDL modules
      id: find-modules
      run: |
        # Find all directories in modules/ that contain both a .wdl file and inputs.json
        modules=()
        for module_dir in modules/*/; do
          if [ -d "$module_dir" ]; then
            module_name=$(basename "$module_dir")
            wdl_file="$module_dir$module_name.wdl"
            inputs_file="$module_dir/inputs.json"
            
            if [ -f "$wdl_file" ] && [ -f "$inputs_file" ]; then
              modules+=("$module_name")
              echo "Found module: $module_name"
            else
              echo "Skipping $module_name - missing required files"
              [ ! -f "$wdl_file" ] && echo "  Missing: $wdl_file"
              [ ! -f "$inputs_file" ] && echo "  Missing: $inputs_file"
            fi
          fi
        done
        
        # Convert array to JSON format for matrix strategy
        if [ ${#modules[@]} -eq 0 ]; then
          modules_json="[]"
        else
          modules_json=$(printf '%s\n' "${modules[@]}" | jq -R . | jq -s -c .)
        fi
        echo "modules=$modules_json" >> $GITHUB_OUTPUT
        echo "Found modules: $modules_json"

  download-test-data:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Download test data
      run: |
        mkdir -p test-data

        # Download chromosome 22 fasta
        wget -q -O test-data/chr22.fa.gz http://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr22.fa.gz
        gunzip test-data/chr22.fa.gz

        # Download chromosome 22 GTF file
        wget -q -O test-data/hg38.ncbiRefSeq.gtf.gz http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/genes/hg38.ncbiRefSeq.gtf.gz
        gunzip test-data/hg38.ncbiRefSeq.gtf.gz
        # Extract only chromosome 22 annotations
        grep "^chr22[[:space:]]" test-data/hg38.ncbiRefSeq.gtf > test-data/chr22.gtf
        rm test-data/hg38.ncbiRefSeq.gtf
        
        # Download a specific version (3.1.1) of the SRA toolkit
        wget -q https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.1.1/sratoolkit.3.1.1-ubuntu64.tar.gz
        tar -xzf sratoolkit.3.1.1-ubuntu64.tar.gz
        echo "$PWD/sratoolkit.3.1.1-ubuntu64/bin" >> $GITHUB_PATH
        export PATH="$PWD/sratoolkit.3.1.1-ubuntu64/bin:$PATH"
        
        # Download a small test RNA-seq sample (SRR13008264 - mouse RNA-seq, ~100MB)
        fasterq-dump --split-files SRR13008264 -O test-data/
        gzip test-data/SRR13008264_1.fastq test-data/SRR13008264_2.fastq
        ls -la test-data/
    - 
      name: Upload test data
      uses: actions/upload-artifact@v4
      with:
        name: test-data
        path: test-data/
        retention-days: 1

  miniwdl-test:
    needs: [discover-modules, download-test-data]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJson(needs.discover-modules.outputs.modules) }}
      fail-fast: false
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Download test data
      uses: actions/download-artifact@v4
      with:
        name: test-data
        path: test-data/
    - 
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - 
      name: Install miniwdl
      run: |
        python -m pip install --upgrade pip
        pip3 install miniwdl
    - 
      name: Run workflow with miniwdl
      run: |
        mkdir -p test-output/miniwdl/${{ matrix.module }}
        module_dir="modules/${{ matrix.module }}"
        wdl_file="$module_dir/${{ matrix.module }}.wdl"
        inputs_file="$module_dir/inputs.json"
        
        echo "Running ${{ matrix.module }} with miniwdl..."
        miniwdl run "$wdl_file" -i "$inputs_file" --dir "test-output/miniwdl/${{ matrix.module }}"
    - 
      name: Display validation report
      run: |
        echo "=== MiniWDL Validation Report ==="
        find test-output/miniwdl -name "validation_report.txt" -exec cat {} \;
  
  cromwell-test:
    needs: [discover-modules, download-test-data]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJson(needs.discover-modules.outputs.modules) }}
      fail-fast: false
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Download test data
      uses: actions/download-artifact@v4
      with:
        name: test-data
        path: test-data/
    - 
      name: Set Up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - 
      name: Download Cromwell
      run: |
        wget -q https://github.com/broadinstitute/cromwell/releases/download/86/cromwell-86.jar
    - 
      name: Run workflow with Cromwell
      run: |
        mkdir -p test-output/cromwell/${{ matrix.module }}
        module_dir="modules/${{ matrix.module }}"
        wdl_file="$module_dir/${{ matrix.module }}.wdl"
        inputs_file="$module_dir/inputs.json"
        options_file="$module_dir/options.json"
        
        echo "Running ${{ matrix.module }} with Cromwell..."
        java -jar cromwell-86.jar run "$wdl_file" -i "$inputs_file" -o "$options_file"
    - 
      name: Display validation report
      run: |
        echo "=== Cromwell Validation Report ==="
        find . -name "validation_report.txt" -exec cat {} \;
  
  sprocket-test:
    needs: [discover-modules, download-test-data]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJson(needs.discover-modules.outputs.modules) }}
      fail-fast: false
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Download test data
      uses: actions/download-artifact@v4
      with:
        name: test-data
        path: test-data/
    - 
      name: Set Up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - 
      name: Install cargo-binstall
      run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - 
      name: Install Sprocket
      run: cargo-binstall sprocket --version 0.12.2
    - 
      name: Run workflow with Sprocket
      run: |
        module_dir="modules/${{ matrix.module }}"
        wdl_file="$module_dir/${{ matrix.module }}.wdl"
        inputs_file="$module_dir/inputs.json"
        
        echo "Running ${{ matrix.module }} with Sprocket..."
        sprocket run --output "test-output/sprocket/${{ matrix.module }}" "$wdl_file" "$inputs_file"
    - 
      name: Display validation report
      run: |
        echo "=== Sprocket Validation Report ==="
        find test-output/sprocket -name "validation_report.txt" -exec cat {} \;
